---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-release-nightly
spec:
  params:
  - name: package
    description: package to release
    default: github.com/tektoncd/pipeline
  - name: imageRegistry
    default: gcr.io/tekton-nightly
  resources:
  - name: source-repo
    type: git
  - name: bucket
    type: storage
  - name: builtKoImage
    type: image
  - name: builtBaseImage
    type: image
  - name: builtEntrypointImage
    type: image
  - name: builtKubeconfigWriterImage
    type: image
  - name: builtCredsInitImage
    type: image
  - name: builtGitInitImage
    type: image
  - name: builtNopImage
    type: image
  - name: builtBashImage
    type: image
  - name: builtGsutilImage
    type: image
  - name: builtControllerImage
    type: image
  - name: builtWebhookImage
    type: image
  - name: builtDigestExporterImage
    type: image
  - name: builtPullRequestInitImage
    type: image
  - name: builtGcsFetcherImage
    type: image
  tasks:
    - name: publish-ko-image
      taskRef:
        name: publish-ci-images
      params:
        - name: imageRegistry
          value: ${params.imageRegistry}
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: builtKoImage
            resource: builtKoImage
    - name: publish-images
      runAfter: [publish-ko-image]
      taskRef:
        name: publish-tekton-pipelines-nightly
      params:
        - name: pathToProject
          value: ${params.package}
        - name: imageRegistry
          value: ${params.imageRegistry}
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: bucket
            resource: bucket
        outputs:
          - name: bucket
            resource: bucket
          - name: builtBaseImage
            resource: builtBaseImage
          - name: builtEntrypointImage
            resource: builtEntrypointImage
          - name: builtKubeconfigWriterImage
            resource: builtKubeconfigWriterImage
          - name: builtCredsInitImage
            resource: builtCredsInitImage
          - name: builtGitInitImage
            resource: builtGitInitImage
          - name: builtNopImage
            resource: builtNopImage
          - name: builtBashImage
            resource: builtBashImage
          - name: builtGsutilImage
            resource: builtGsutilImage
          - name: builtControllerImage
            resource: builtControllerImage
          - name: builtWebhookImage
            resource: builtWebhookImage
          - name: builtDigestExporterImage
            resource: builtDigestExporterImage
          - name: builtPullRequestInitImage
            resource: builtPullRequestInitImage
          - name: builtGcsFetcherImage
            resource: builtGcsFetcherImage
